### ISSUE TITLE
Compared directories are not on the same host

### ISSUE THREAD

**Issue by cjohansson** [fourier/ztree#47]
6 months ago I think ztree-diff worked over TRAMP without any problems but now I get the error "Compared directories are not on the same host". Is it possible to enable diffs between different hosts?

**Comment by fourier** [comment]
@Silex Could you take a look at this?

**Comment by Silex** [comment]
@cjohansson: there's no way ztree-diff worked over TRAMP for directories on different hosts...

What happened if you did is that ztree probably reported everything as "different" (or similar). What has changed since then is simply a check that reports an error if you try to compare unsupported things.

For the implementation, ztree just runs `diff -r $DIR1 $DIR2`. When over TRAMP, this command is run on the remote host. It makes no sense to run that command with different hosts.

The only way to achieve what you want would be to implement the diff as elisp, and download each file and diff them and that would be horribly slow.

**Comment by cjohansson** [comment]
I see, yes you are correct. I think it labeled all files on a different host as changed.

**Comment by Silex** [comment]
:+1:
